AllCops:
  UseCache: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
  # Include:
  Exclude:
    - 'Gemfile'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - '**/Rakefile'
    - '**/config.ru'

StringLiterals:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

# Rails:
#   Enabled: true

Metrics/LineLength:
  Max: 90

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/ExtraSpacing:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false
